DROP DATABASE IF EXISTS EXO;
CREATE DATABASE EXO;
USE EXO;

CREATE TABLE contacts(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
nom VARCHAR(70) NOT NULL,
prenom VARCHAR(70) NOT NULL,
date_de_naissance DATE,
sexe VARCHAR(20),
adresse TEXT NOT NULL,
cp VARCHAR(20) NOT NULL,
ville VARCHAR(70) NOT NULL,
pays_iso_3 VARCHAR(3) NOT NULL,
);

CREATE TABLE pays(
iso_3 VARCHAR(3) NOT NULL,
nom VARCHAR(70) NOT NULL,
iso_2 VARCHAR(2) NOT NULL,
nationalite VARCHAR(50) NOT NULL,
);

CREATE TABLE telephone(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
id_contact BIGINT PRIMARY KEY AUTO_INCREMENT,
numero VARCHAR(50)
type VARCHAR,
);